name: cicd

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.9.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest
          push-args: --disable-content-trust

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set target environment
    run: |
      STATUS=$(curl -o /dev/null -w "%{http_code}" "http://${{ secrets.HOST }}/api/env")
      if [ $STATUS -eq 200 ]; then
        CURRENT_ENV=$(curl -s "http://${{ secrets.HOST }}/api/env")
      else
        CURRENT_ENV=green
      fi
      echo "CURRENT_ENV=$CURRENT_ENV" >> $GITHUB_ENV
      if [ "$CURRENT_ENV" == "blue" ]; then
        echo "PORT=3001" >> $GITHUB_ENV
        echo "TARGET_ENV=green" >> $GITHUB_ENV
      else
        echo "PORT=3000" >> $GITHUB_ENV
        echo "TARGET_ENV=blue" >> $GITHUB_ENV
      fi


      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest
            docker-compose -f docker-compose-${{ env.TARGET_ENV }}.yml up -d
            docker-compose -f docker-compose-${{ env.CURRENT_ENV }}.yml stop

      - name: Update NGINX configuration
        uses: appleboy/ssh-action@v0.1.10
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.NGINX_HOST }}
          key: ${{ secrets.NGINX_SSH_KEY }}
          script: |
            sudo sed -i "s/set \$service_url .*;/set \$service_url ${{ env.TARGET_ENV }};/g" /etc/nginx/conf.d/service-env.inc
            sudo nginx -s reload






deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # 대상 IP를 설정
      - name: Set target IP (MAIN)
        run: |
          STATUS=$(curl -o /dev/null -w "%{http_code}" "https://${{ secrets.MAIN_NGINX_EC2_DOMAIN }}/api/env")
          echo $STATUS
          if [ $STATUS = 200 ]; then
            CURRENT_UPSTREAM=$(curl -s "https://${{ secrets.MAIN_NGINX_EC2_DOMAIN }}/api/env")
          else
            CURRENT_UPSTREAM=green
          fi
          echo CURRENT_UPSTREAM=$CURRENT_UPSTREAM >> $GITHUB_ENV
          if [ $CURRENT_UPSTREAM = blue ]; then
            echo "CURRENT_PORT1=3000" >> $GITHUB_ENV     
            echo "STOPPED_PORT1=3001" >> $GITHUB_ENV
            echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
          elif [ $CURRENT_UPSTREAM = green ]; then
            echo "CURRENT_PORT1=3001" >> $GITHUB_ENV
            echo "STOPPED_PORT1=3000" >> $GITHUB_ENV
            echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
          else
            echo "error"
            exit 1
          fi

      # Docker Compose를 사용하여 컨테이너를 배포1
      - name: Docker compose (MAIN)
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOST }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            cd server
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME}}/puzzle:latest
            sudo docker-compose -f docker-compose-${{env.TARGET_UPSTREAM}}.yml up -d

      # Docker Compose를 사용하여 컨테이너를 배포2
      - name: Docker compose (MAIN)
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOST2 }}
          key: ${{ secrets.EC2_SSH_KEY_2 }}
          script_stop: true
          script: |
            cd server
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME}}/puzzle:latest
            sudo docker-compose -f docker-compose-${{env.TARGET_UPSTREAM}}.yml up -d


      # 배포된 서버 URL을 확인
      - name: Check deploy server URL (MAIN)
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://${{ secrets.HOST }}:${{env.STOPPED_PORT1}}/api/env
          max-attempts: 5
          retry-delay: 10s

      # Nginx의 upstream을 변경1
      - name: Change nginx upstream (MAIN)
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOST }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            sudo docker exec -i nginxServer bash -c 'echo "set \$service_url ${{ env.TARGET_UPSTREAM }};" > /etc/nginx/conf.d/service-env.inc && nginx -s reload' 


      # 현재 서버를 중지1
      - name: Stop current server (MAIN)
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOST }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            sudo docker stop ${{env.CURRENT_UPSTREAM}} 
            sudo docker rm ${{env.CURRENT_UPSTREAM}}

      # 현재 서버를 중지2
      - name: Stop current server (MAIN)
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOST2 }}
          key: ${{ secrets.EC2_SSH_KEY_2 }}
          script_stop: true
          script: |
            sudo docker stop ${{env.CURRENT_UPSTREAM}} 
            sudo docker rm ${{env.CURRENT_UPSTREAM}}